trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

# =========================
# STAGE 1 - BUILD
# =========================
- stage: Build
  displayName: 'Build'

  jobs:
  - job: BuildJob
    displayName: 'Build Vite React Application'

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build React Application'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/dist'
        artifact: 'react-build'
      displayName: 'Publish Build Artifact'


# =========================
# STAGE 2 - TEST
# =========================
- stage: Test
  displayName: 'Test'

  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: TestJob
    displayName: 'Run Automated Tests'

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm test
      displayName: 'Run Automated Tests'


# =========================
# STAGE 3 - DEPLOY
# =========================
- stage: Deploy
  displayName: 'Deploy'

  dependsOn: Test
  condition: succeeded()

  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure VM'

    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'react-build'
        path: '$(Pipeline.Workspace)/react-build'
      displayName: 'Download Build Artifact'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'AzureVM'
        sourceFolder: '$(Pipeline.Workspace)/react-build'
        contents: '**'
        targetFolder: '/tmp/agriwise-dist'
        overwrite: true
      displayName: 'Copy Build to Azure VM'

    - task: SSH@0
      inputs:
        sshEndpoint: 'AzureVM'
        runOptions: 'inline'
        inline: |
          sudo rm -rf /var/www/html/*
          sudo cp -r /tmp/agriwise-dist/* /var/www/html/
          sudo systemctl restart nginx
      displayName: 'Deploy to Nginx'